//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ehecatl.DymosWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.cls.wwg.dymos.com", ConfigurationName="DymosWebService.StockWSPortType")]
    public interface StockWSPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:InsertStockWS", ReplyAction="urn:InsertStockWSResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Ehecatl.DymosWebService.InsertStockWSResponse InsertStockWS(Ehecatl.DymosWebService.InsertStockWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:InsertStockWS", ReplyAction="urn:InsertStockWSResponse")]
        System.Threading.Tasks.Task<Ehecatl.DymosWebService.InsertStockWSResponse> InsertStockWSAsync(Ehecatl.DymosWebService.InsertStockWSRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://model.cls.wwg.dymos.com/xsd")]
    public partial class StockWSDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string item_cdField;
        
        private string ret_codeField;
        
        private string ret_msgField;
        
        private string stock_qtyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string item_cd {
            get {
                return this.item_cdField;
            }
            set {
                this.item_cdField = value;
                this.RaisePropertyChanged("item_cd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ret_code {
            get {
                return this.ret_codeField;
            }
            set {
                this.ret_codeField = value;
                this.RaisePropertyChanged("ret_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ret_msg {
            get {
                return this.ret_msgField;
            }
            set {
                this.ret_msgField = value;
                this.RaisePropertyChanged("ret_msg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string stock_qty {
            get {
                return this.stock_qtyField;
            }
            set {
                this.stock_qtyField = value;
                this.RaisePropertyChanged("stock_qty");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStockWS", WrapperNamespace="http://ws.cls.wwg.dymos.com", IsWrapped=true)]
    public partial class InsertStockWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cls.wwg.dymos.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string vendor_cd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cls.wwg.dymos.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("stockWSDTO", IsNullable=true)]
        public Ehecatl.DymosWebService.StockWSDTO[] stockWSDTO;
        
        public InsertStockWSRequest() {
        }
        
        public InsertStockWSRequest(string vendor_cd, Ehecatl.DymosWebService.StockWSDTO[] stockWSDTO) {
            this.vendor_cd = vendor_cd;
            this.stockWSDTO = stockWSDTO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InsertStockWSResponse", WrapperNamespace="http://ws.cls.wwg.dymos.com", IsWrapped=true)]
    public partial class InsertStockWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.cls.wwg.dymos.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Ehecatl.DymosWebService.StockWSDTO[] @return;
        
        public InsertStockWSResponse() {
        }
        
        public InsertStockWSResponse(Ehecatl.DymosWebService.StockWSDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockWSPortTypeChannel : Ehecatl.DymosWebService.StockWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockWSPortTypeClient : System.ServiceModel.ClientBase<Ehecatl.DymosWebService.StockWSPortType>, Ehecatl.DymosWebService.StockWSPortType {
        
        public StockWSPortTypeClient() {
        }
        
        public StockWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ehecatl.DymosWebService.InsertStockWSResponse Ehecatl.DymosWebService.StockWSPortType.InsertStockWS(Ehecatl.DymosWebService.InsertStockWSRequest request) {
            return base.Channel.InsertStockWS(request);
        }
        
        public Ehecatl.DymosWebService.StockWSDTO[] InsertStockWS(string vendor_cd, Ehecatl.DymosWebService.StockWSDTO[] stockWSDTO) {
            Ehecatl.DymosWebService.InsertStockWSRequest inValue = new Ehecatl.DymosWebService.InsertStockWSRequest();
            inValue.vendor_cd = vendor_cd;
            inValue.stockWSDTO = stockWSDTO;
            Ehecatl.DymosWebService.InsertStockWSResponse retVal = ((Ehecatl.DymosWebService.StockWSPortType)(this)).InsertStockWS(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ehecatl.DymosWebService.InsertStockWSResponse> Ehecatl.DymosWebService.StockWSPortType.InsertStockWSAsync(Ehecatl.DymosWebService.InsertStockWSRequest request) {
            return base.Channel.InsertStockWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ehecatl.DymosWebService.InsertStockWSResponse> InsertStockWSAsync(string vendor_cd, Ehecatl.DymosWebService.StockWSDTO[] stockWSDTO) {
            Ehecatl.DymosWebService.InsertStockWSRequest inValue = new Ehecatl.DymosWebService.InsertStockWSRequest();
            inValue.vendor_cd = vendor_cd;
            inValue.stockWSDTO = stockWSDTO;
            return ((Ehecatl.DymosWebService.StockWSPortType)(this)).InsertStockWSAsync(inValue);
        }
    }
}
